apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 20s
    count: 5
    successCondition: result[0] >= 0.95
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local:80
        query: |
          sum(rate(
            http_requests_total{service="{{args.service-name}}",status=~"2.*"}[5m])
          ) 
          /
          sum(rate(
            http_requests_total{service="{{args.service-name}}"}[5m])
          )