apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 20s
    count: 1
    # Always pass the analysis
    successCondition: "true"
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: success
                image: alpine:3.18
                command: ["sh", "-c", "echo Analysis successful; exit 0"]
              restartPolicy: Never
          backoffLimit: 0