{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-path: /health/liveness
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateARN | default "" }} #dynamically reference the ACM certificate in your Kubernetes ingress while supporting complete redeploys
    # This specific format is required for ALB to work with Argo Rollouts
    alb.ingress.kubernetes.io/actions.traffic-split: |
      {
        "type": "forward",
        "forwardConfig": {
          "targetGroups": [
            {
              "serviceName": "{{ include "webapp.fullname" . }}-stable",
              "servicePort": "80",
              "weight": 100
            },
            {
              "serviceName": "{{ include "webapp.fullname" . }}-canary",
              "servicePort": "80",
              "weight": 0
            }
          ]
        }
      }
    alb.ingress.kubernetes.io/tags: service=webapp,environment={{ .Values.environment | default "dev" }}
    alb.ingress.kubernetes.io/group.name: webapp
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: "www.thegriffinfamily.link"
      http:
        paths:
          # This path must exactly match the rootService configuration
          - path: /
            pathType: Prefix
            backend:
              # Use the traffic-split action
              service:
                name: traffic-split
                port:
                  number: 80
          # Add a direct path to the stable service for health checks/etc
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "webapp.fullname" . }}-stable
                port:
                  number: 80
  tls:
    - hosts:
        - "www.thegriffinfamily.link"
      secretName: tls-secret
{{- end }}