apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http