apiVersion: v1
kind: Service
metadata:
  name: traffic-split
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http