apiVersion: v1
kind: Service
metadata:
  name: traffic-split
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: dummy.local
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http