replicaCount: 2

image: 
  repository: thegriffinfamily-link-resume-repo
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: www.thegriffinfamily.link
      paths:
        - path: /resumes/mike
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}