replicaCount: 2


# Simple image string that GitHub Action will replace
image: 251374076386.dkr.ecr.us-east-1.amazonaws.com/thegriffinfamily-link-resume-repo:b202a5d81ecb0c878bb87ff9a991d08af6c52982

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Keep basic annotations here that don't change between environments; other annotations will be passed in at runtime through the application.yml workflow
  hosts:
    - host: www.thegriffinfamily.link
      paths:
        - path: /resumes/mike
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - www.thegriffinfamily.link

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}