replicaCount: 2

# Simple image string that GitHub Action will replace
image: 251374076386.dkr.ecr.us-east-1.amazonaws.com/thegriffinfamily-link-resume-repo:76d1cb6ec50098fc7c5f33bb468a48f3dfa3b152

# Add this parameter for gunicorn workers
gunicornWorkers: "2"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: alb  # Use this instead of kubernetes.io/ingress.class annotation
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # Add health check annotation for ALB
    alb.ingress.kubernetes.io/healthcheck-path: /health/liveness
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
  hosts:
    - host: www.thegriffinfamily.link
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - www.thegriffinfamily.link

# Add sensible resource limits
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Add autoscaling parameters
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}