replicaCount: 2


# Simple image string that GitHub Action will replace
image: 251374076386.dkr.ecr.us-east-1.amazonaws.com/thegriffinfamily-link-resume-repo:4c3f4c54ebc72c8577d412eb6e45e44f80390da7

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Keep basic annotations here that don't change between environments; other annotations will be passed in at runtime through the application.yml workflow
  hosts:
    - host: www.thegriffinfamily.link
      paths:
        - path: /
          pathType: Prefix
        - path: /resumes/mike
          pathType: Exact
  tls:
    - hosts:
        - www.thegriffinfamily.link

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}