replicaCount: 2


# Simple image string that GitHub Action will replace
image: 251374076386.dkr.ecr.us-east-1.amazonaws.com/thegriffinfamily-link-resume-repo:80ee4eb24a5cef04b981ca7c7183b8490c03db14

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: alb  # Use this instead of kubernetes.io/ingress.class annotation
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
  hosts:
    - host: www.thegriffinfamily.link
      paths:
        - path: /
          pathType: Prefix
        - path: /resumes/mike
          pathType: Exact
  tls:
    - hosts:
        - www.thegriffinfamily.link

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}