name: Build and Update Image

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - '.github/workflows/application.yml'
      - 'helm/webapp/**'
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        default: 'deploy'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    # permissions required for OIDC authentication
    permissions:
      id-token: write
      contents: write  # Changed from 'read' to 'write' to allow git push
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::251374076386:role/GriffinFamily.Link.TF"
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Fix Chart.yaml case sensitivity
        run: |
          if [ -f helm/webapp/chart.yaml ] && [ ! -f helm/webapp/Chart.yaml ]; then
            mv helm/webapp/chart.yaml helm/webapp/Chart.yaml
          fi

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: thegriffinfamily-link-resume-repo
          IMAGE_TAG: ${{ github.sha }}
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/thegriffinfamily-link-resume-repo:${{ github.sha }}
        run: |
          # Build Docker image with the tag
          cd app
          docker build -t $IMAGE .
          
          # Push the image to ECR
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Helm values
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Update the image value in values.yaml
          sed -i "s|image:.*|image: ${{ env.IMAGE }}|g" helm/webapp/values.yaml
          
          # Commit and push the changes
          git add helm/webapp/values.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}